# Generated by Django 5.1.1 on 2024-11-07 23:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssChanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('active', 'active'), ('disable', 'disable')], default='active', max_length=50)),
                ('is_new', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RssParser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('active', 'active'), ('disable', 'disable')], default='active', max_length=50)),
                ('is_new', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('frequency', models.IntegerField(default=60)),
                ('elements', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Rss',
        ),
    ]
