# Generated by Django 5.1.1 on 2024-11-11 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rsschanel_rssparser_delete_rss'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('source', models.JSONField()),
                ('status', models.CharField(choices=[('active', 'active'), ('disable', 'disable')], default='active', max_length=50)),
                ('type', models.CharField(choices=[('generator', 'generator'), ('builder', 'builder')], max_length=50)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='RssChanel',
        ),
        migrations.DeleteModel(
            name='RssParser',
        ),
    ]
