# Generated by Django 5.1.1 on 2024-11-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rsschannel_delete_rsschanel_delete_rssparser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsschannel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
