# Generated by Django 5.1.1 on 2024-11-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_rsschannel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsschannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
