# Generated by Django 5.1.1 on 2024-11-07 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('site_id', models.TextField()),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField()),
                ('image', models.URLField()),
                ('summary', models.TextField()),
                ('author', models.CharField(max_length=256)),
                ('published', models.DateTimeField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app.rssgroup')),
            ],
        ),
    ]
