# Generated by Django 5.1.1 on 2024-11-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rssgroup_articalcollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticalCollection',
            new_name='ArticleCollection',
        ),
    ]
