# Generated by Django 5.1.1 on 2024-11-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_articalcollection_articlecollection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='group_id',
            new_name='collection_id',
        ),
    ]
