# Generated by Django 5.1.1 on 2024-11-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_group_id_article_collection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
