# Generated by Django 5.1.2 on 2024-11-01 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_id_alter_subscriptiontype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
